
import { Country, Accommodation, Guide, Flight, Restaurant, Car, TourActivity } from '../types';

export const ACCOMMODATIONS: Accommodation[] = [
  // --- HOTELS (10) ---
  {
    id: 'h1',
    name: 'Mara Treehouse',
    type: 'Hotel',
    country: Country.KENYA,
    district: 'Maasai Mara',
    price: 350,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1493246507139-91e8bef99c02?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1493246507139-91e8bef99c02?auto=format&fit=crop&q=80'],
    activities: ['Wildlife', 'Photography'],
    description: 'A luxurious treehouse overlooking the Savannah.',
    lat: -1.48,
    lng: 35.12
  },
  {
    id: 'h2',
    name: 'Nile River Explorer Camp',
    type: 'Hotel',
    country: Country.UGANDA,
    district: 'Jinja',
    price: 120,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80'],
    activities: ['Rafting', 'Hiking'],
    description: 'The premier camp for adrenaline seekers in Jinja.',
    lat: 0.42,
    lng: 33.18
  },
  {
    id: 'h3',
    name: 'Bwindi Forest Lodge',
    type: 'Hotel',
    country: Country.UGANDA,
    district: 'Kabale',
    price: 450,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&q=80'],
    activities: ['Trekking', 'Birding'],
    description: 'Steps away from the gorilla trekking starting point.',
    lat: -1.04,
    lng: 29.69
  },
  {
    id: 'h4',
    name: 'Giraffe Manor',
    type: 'Hotel',
    country: Country.KENYA,
    district: 'Nairobi',
    price: 800,
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80'],
    activities: ['Wildlife', 'Relaxation'],
    description: 'An exclusive boutique hotel where giraffes visit for breakfast.',
    lat: -1.37,
    lng: 36.74
  },
  {
    id: 'h5',
    name: 'Serengeti Serena Lodge',
    type: 'Hotel',
    country: Country.TANZANIA,
    district: 'Serengeti',
    price: 520,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&q=80'],
    activities: ['Wildlife', 'Photography'],
    description: 'A blend of high-safari adventure and state-of-the-art luxury.',
    lat: -2.33,
    lng: 34.83
  },
  {
    id: 'h6',
    name: 'Zanzibar Serena Hotel',
    type: 'Hotel',
    country: Country.TANZANIA,
    district: 'Zanzibar',
    price: 380,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80'],
    activities: ['Beach', 'Relaxation'],
    description: 'Swahili-styled luxury on the edge of the Indian Ocean.',
    lat: -6.16,
    lng: 39.20
  },
  {
    id: 'h7',
    name: 'Wildwaters Lodge',
    type: 'Hotel',
    country: Country.UGANDA,
    district: 'Jinja',
    price: 410,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80'],
    activities: ['Relaxation', 'Hiking'],
    description: 'Perched on a private island in the middle of the Nile rapids.',
    lat: 0.44,
    lng: 33.19
  },
  {
    id: 'h8',
    name: 'The Norfolk Hotel',
    type: 'Hotel',
    country: Country.KENYA,
    district: 'Nairobi',
    price: 250,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80'],
    activities: ['Photography', 'Relaxation'],
    description: 'A landmark of Kenya\'s history, offering colonial charm and modern luxury.',
    lat: -1.27,
    lng: 36.81
  },
  {
    id: 'h9',
    name: 'Ngorongoro Farmhouse',
    type: 'Hotel',
    country: Country.TANZANIA,
    district: 'Arusha',
    price: 290,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80'],
    activities: ['Hiking', 'Photography'],
    description: 'A coffee plantation lodge providing spectacular crater views.',
    lat: -3.36,
    lng: 36.68
  },
  {
    id: 'h10',
    name: 'Protea Hotel Entebbe',
    type: 'Hotel',
    country: Country.UGANDA,
    district: 'Entebbe',
    price: 210,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80'],
    activities: ['Relaxation', 'Birding'],
    description: 'Located on the shores of Lake Victoria, near Entebbe International Airport.',
    lat: 0.04,
    lng: 32.44
  },

  // --- AIRBNB (10) ---
  {
    id: 'a1',
    name: 'Zanzibar Beach Loft',
    type: 'Airbnb',
    country: Country.TANZANIA,
    district: 'Zanzibar',
    price: 180,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80'],
    activities: ['Beach', 'Relaxation'],
    description: 'Modern minimalist loft with private beach access.',
    lat: -6.16,
    lng: 39.20
  },
  {
    id: 'a2',
    name: 'Nile View A-Frame',
    type: 'Airbnb',
    country: Country.UGANDA,
    district: 'Jinja',
    price: 95,
    rating: 4.95,
    image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80'],
    activities: ['Relaxation', 'Hiking'],
    description: 'Eco-friendly A-frame cabin with panoramic views of the Nile.',
    lat: 0.44,
    lng: 33.20
  },
  {
    id: 'a3',
    name: 'Nairobi Boho Studio',
    type: 'Airbnb',
    country: Country.KENYA,
    district: 'Nairobi',
    price: 65,
    rating: 4.85,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80'],
    activities: ['Photography'],
    description: 'Chic studio in the heart of Kilimani, perfect for digital nomads.',
    lat: -1.29,
    lng: 36.82
  },
  {
    id: 'a4',
    name: 'Serengeti Glamping Pod',
    type: 'Airbnb',
    country: Country.TANZANIA,
    district: 'Serengeti',
    price: 210,
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&q=80'],
    activities: ['Wildlife', 'Birding'],
    description: 'Solar-powered pod in the wild. Experience the migration from your bed.',
    lat: -2.33,
    lng: 34.83
  },
  {
    id: 'a5',
    name: 'Bamboo House Kabale',
    type: 'Airbnb',
    country: Country.UGANDA,
    district: 'Kabale',
    price: 85,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&q=80'],
    activities: ['Hiking', 'Birding'],
    description: 'Quaint bamboo cottage overlooking the terraced hills of Kigezi.',
    lat: -1.25,
    lng: 29.98
  },
  {
    id: 'a6',
    name: 'Coastal Villa Mombasa',
    type: 'Airbnb',
    country: Country.KENYA,
    district: 'Mombasa',
    price: 150,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80'],
    activities: ['Beach', 'Photography'],
    description: 'Stunning 4-bedroom villa with a private infinity pool.',
    lat: -4.04,
    lng: 39.66
  },
  {
    id: 'a7',
    name: 'Arusha Eco-Lodge',
    type: 'Airbnb',
    country: Country.TANZANIA,
    district: 'Arusha',
    price: 110,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80'],
    activities: ['Hiking', 'Wildlife'],
    description: 'Sustainable living at the base of Mount Meru.',
    lat: -3.37,
    lng: 36.68
  },
  {
    id: 'a8',
    name: 'Lakeview Studio Nakuru',
    type: 'Airbnb',
    country: Country.KENYA,
    district: 'Nakuru',
    price: 55,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80'],
    activities: ['Birding', 'Wildlife'],
    description: 'Modern studio with a balcony viewing Lake Nakuru National Park.',
    lat: -0.30,
    lng: 36.06
  },
  {
    id: 'a9',
    name: 'Swahili House Zanzibar',
    type: 'Airbnb',
    country: Country.TANZANIA,
    district: 'Zanzibar',
    price: 130,
    rating: 4.85,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80'],
    activities: ['Photography', 'Relaxation'],
    description: 'Restored historic house in the heart of Stone Town.',
    lat: -6.16,
    lng: 39.21
  },
  {
    id: 'a10',
    name: 'Kampala Urban Loft',
    type: 'Airbnb',
    country: Country.UGANDA,
    district: 'Kampala',
    price: 75,
    rating: 4.75,
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&q=80'],
    activities: ['Relaxation', 'Photography'],
    description: 'Industrial-chic loft in the vibrant neighborhood of Kololo.',
    lat: 0.31,
    lng: 32.58
  }
];

export const GUIDES: Guide[] = [
  {
    id: 'g1',
    name: 'Musoke D.',
    bio: '15 years experience in primate tracking and forest conservation.',
    country: Country.UGANDA,
    location: 'Bwindi',
    languages: ['English', 'Luganda', 'Swahili'],
    expertise: ['Trekking', 'Birding'],
    rating: 5,
    reviews: 120,
    image: 'https://picsum.photos/seed/guide1/300/300',
    age: 42,
    gender: 'Male',
    experienceYears: 15
  },
  {
    id: 'g2',
    name: 'Sarah M.',
    bio: 'Wildlife biologist and specialized photography guide in the Savannah.',
    country: Country.KENYA,
    location: 'Maasai Mara',
    languages: ['English', 'French', 'Swahili'],
    expertise: ['Wildlife', 'Photography'],
    rating: 4.9,
    reviews: 85,
    image: 'https://picsum.photos/seed/guide2/300/300',
    age: 29,
    gender: 'Female',
    experienceYears: 7
  },
  {
    id: 'g3',
    name: 'Jean-Pierre',
    bio: 'Arusha local with deep knowledge of Serengeti routes and Kilimanjaro.',
    country: Country.TANZANIA,
    location: 'Arusha',
    languages: ['French', 'English', 'Swahili'],
    expertise: ['Wildlife', 'Hiking'],
    rating: 5,
    reviews: 210,
    image: 'https://picsum.photos/seed/guide3/300/300',
    age: 38,
    gender: 'Male',
    experienceYears: 12
  },
  {
    id: 'g4',
    name: 'Kato B.',
    bio: 'Expert birdwatcher and historical guide for Kampala city tours.',
    country: Country.UGANDA,
    location: 'Kampala',
    languages: ['English', 'Luganda'],
    expertise: ['Birding', 'Photography'],
    rating: 4.8,
    reviews: 45,
    image: 'https://picsum.photos/seed/guide4/300/300',
    age: 31,
    gender: 'Male',
    experienceYears: 8
  },
  {
    id: 'g5',
    name: 'Amani S.',
    bio: 'Passionate wildlife scout specializing in leopard sightings.',
    country: Country.TANZANIA,
    location: 'Serengeti',
    languages: ['Swahili', 'English', 'German'],
    expertise: ['Wildlife', 'Photography'],
    rating: 4.95,
    reviews: 130,
    image: 'https://picsum.photos/seed/guide5/300/300',
    age: 35,
    gender: 'Female',
    experienceYears: 10
  },
  {
    id: 'g6',
    name: 'Mwikali J.',
    bio: 'Nairobi-based guide with a focus on conservation and rhino protection.',
    country: Country.KENYA,
    location: 'Nairobi',
    languages: ['English', 'Swahili'],
    expertise: ['Wildlife', 'Birding'],
    rating: 4.7,
    reviews: 62,
    image: 'https://picsum.photos/seed/guide6/300/300',
    age: 26,
    gender: 'Female',
    experienceYears: 4
  },
  {
    id: 'g7',
    name: 'Otim R.',
    bio: 'Whitewater rafting expert and source-of-the-Nile historian.',
    country: Country.UGANDA,
    location: 'Jinja',
    languages: ['English', 'Lusoga'],
    expertise: ['Rafting', 'Hiking'],
    rating: 5.0,
    reviews: 180,
    image: 'https://picsum.photos/seed/guide7/300/300',
    age: 33,
    gender: 'Male',
    experienceYears: 11
  },
  {
    id: 'g8',
    name: 'Fatuma K.',
    bio: 'Zanzibar spice tour specialist and culinary historian.',
    country: Country.TANZANIA,
    location: 'Zanzibar',
    languages: ['Arabic', 'Swahili', 'English'],
    expertise: ['Relaxation', 'Photography'],
    rating: 4.9,
    reviews: 95,
    image: 'https://picsum.photos/seed/guide8/300/300',
    age: 40,
    gender: 'Female',
    experienceYears: 18
  },
  {
    id: 'g9',
    name: 'Samuel L.',
    bio: 'Traditional Maasai guide with wisdom in tracking and flora.',
    country: Country.KENYA,
    location: 'Maasai Mara',
    languages: ['Swahili', 'English', 'Maasai'],
    expertise: ['Wildlife', 'Trekking'],
    rating: 5.0,
    reviews: 320,
    image: 'https://picsum.photos/seed/guide9/300/300',
    age: 45,
    gender: 'Male',
    experienceYears: 20
  },
  {
    id: 'g10',
    name: 'Grace W.',
    bio: 'Ornithologist specializing in Rift Valley bird species.',
    country: Country.KENYA,
    location: 'Nakuru',
    languages: ['English', 'Swahili'],
    expertise: ['Birding', 'Wildlife'],
    rating: 4.85,
    reviews: 55,
    image: 'https://picsum.photos/seed/guide10/300/300',
    age: 37,
    gender: 'Female',
    experienceYears: 14
  }
];

export const FLIGHTS: Flight[] = [
  { id: 'f1', airline: 'Qatar Airways', from: 'LHR', to: 'EBB', price: 650, duration: '12h 30m', time: '08:00 AM', stops: 1, departureDate: '2024-12-15' },
  { id: 'f2', airline: 'Kenya Airways', from: 'LHR', to: 'NBO', price: 580, duration: '9h 15m', time: '10:00 PM', stops: 0, departureDate: '2024-12-16' },
  { id: 'f3', airline: 'Ethiopian', from: 'JFK', to: 'DAR', price: 920, duration: '18h 45m', time: '11:30 AM', stops: 1, departureDate: '2024-12-17' },
  { id: 'f4', airline: 'Brussels Airlines', from: 'BRU', to: 'EBB', price: 450, duration: '8h 20m', time: '09:00 PM', stops: 0, departureDate: '2024-12-15' },
  { id: 'f5', airline: 'Emirates', from: 'DXB', to: 'NBO', price: 420, duration: '5h 10m', time: '02:00 PM', stops: 0, departureDate: '2024-12-18' },
  { id: 'f6', airline: 'Qatar Airways', from: 'DOH', to: 'DAR', price: 480, duration: '6h 00m', time: '01:30 AM', stops: 0, departureDate: '2024-12-19' },
  { id: 'f7', airline: 'KLM', from: 'AMS', to: 'EBB', price: 720, duration: '10h 40m', time: '10:15 AM', stops: 1, departureDate: '2024-12-15' },
  { id: 'f8', airline: 'Turkish Airlines', from: 'IST', to: 'NBO', price: 550, duration: '6h 45m', time: '08:45 PM', stops: 0, departureDate: '2024-12-20' },
  { id: 'f9', airline: 'Kenya Airways', from: 'AMS', to: 'NBO', price: 610, duration: '11h 00m', time: '11:00 AM', stops: 1, departureDate: '2024-12-16' },
  { id: 'f10', airline: 'Air Uganda', from: 'EBB', to: 'NBO', price: 150, duration: '1h 15m', time: '07:30 AM', stops: 0, departureDate: '2024-12-21' }
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'r1',
    name: 'The Lawns Wild Game',
    cuisine: ['Steakhouse', 'African', 'Fine Dining'],
    priceLevel: 4,
    rating: 4.8,
    reviews: 850,
    district: 'Kampala',
    country: Country.UGANDA,
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80',
    description: 'Specializing in fusion wild game from across Africa in a lush garden setting.'
  },
  {
    id: 'r2',
    name: 'Carnivore Nairobi',
    cuisine: ['Barbecue', 'African'],
    priceLevel: 3,
    rating: 4.7,
    reviews: 2400,
    district: 'Nairobi',
    country: Country.KENYA,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80',
    description: 'An open-air brassiere that treats you to an all-you-can-eat meat feast.'
  },
  {
    id: 'r3',
    name: 'Emerson on Hurumzi',
    cuisine: ['Zanzibari', 'Seafood', 'Rooftop'],
    priceLevel: 4,
    rating: 4.9,
    reviews: 420,
    district: 'Zanzibar',
    country: Country.TANZANIA,
    image: 'https://images.unsplash.com/photo-1533777324565-a040eb52faad?auto=format&fit=crop&q=80',
    description: 'Authentic Persian-Zanzibari cuisine on Stone Town\'s highest rooftop.'
  },
  {
    id: 'r4',
    name: '2K Restaurant',
    cuisine: ['Local', 'African'],
    priceLevel: 1,
    rating: 4.5,
    reviews: 1200,
    district: 'Kampala',
    country: Country.UGANDA,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80',
    description: 'The spot for authentic Luwombo and local Ugandan staples.'
  },
  {
    id: 'r5',
    name: 'Seven Seafood & Grill',
    cuisine: ['Seafood', 'International'],
    priceLevel: 4,
    rating: 4.6,
    reviews: 560,
    district: 'Nairobi',
    country: Country.KENYA,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80',
    description: 'Nairobi\'s premier destination for Indian Ocean seafood.'
  },
  {
    id: 'r6',
    name: 'Café Javas',
    cuisine: ['International', 'Coffee'],
    priceLevel: 2,
    rating: 4.7,
    reviews: 1500,
    district: 'Kampala',
    country: Country.UGANDA,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80',
    description: 'Known for generous portions and exceptional service in a modern setting.'
  },
  {
    id: 'r7',
    name: 'The Talisman',
    cuisine: ['Eclectic', 'Fusion'],
    priceLevel: 3,
    rating: 4.8,
    reviews: 1100,
    district: 'Nairobi',
    country: Country.KENYA,
    image: 'https://images.unsplash.com/photo-1550966841-3ee20412e87a?auto=format&fit=crop&q=80',
    description: 'An elegant, multi-cuisine restaurant with a beautiful outdoor garden.'
  },
  {
    id: 'r8',
    name: 'Lukmaan Restaurant',
    cuisine: ['Local', 'Zanzibari'],
    priceLevel: 1,
    rating: 4.6,
    reviews: 1800,
    district: 'Zanzibar',
    country: Country.TANZANIA,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80',
    description: 'Stone Town\'s most famous local spot for biryani and Zanzibar pizza.'
  },
  {
    id: 'r9',
    name: 'Fogo Gaucho',
    cuisine: ['Brazilian', 'Steakhouse'],
    priceLevel: 3,
    rating: 4.7,
    reviews: 980,
    district: 'Nairobi',
    country: Country.KENYA,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80',
    description: 'Nairobi\'s ultimate Brazilian rodizio experience.'
  },
  {
    id: 'r10',
    name: 'Mediterraneo',
    cuisine: ['Italian', 'Seafood'],
    priceLevel: 3,
    rating: 4.5,
    reviews: 740,
    district: 'Dar es Salaam',
    country: Country.TANZANIA,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80',
    description: 'Italian dining with a view of the Indian Ocean.'
  }
];

export const CARS: Car[] = [
  {
    id: 'c1',
    name: 'Toyota Land Cruiser V8',
    type: 'SUV',
    transmission: 'Automatic',
    capacity: 7,
    pricePerDay: 150,
    image: 'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&q=80',
    country: Country.UGANDA,
    district: 'Kampala',
    features: ['A/C', 'Bluetooth', '4WD', 'Roof Rack']
  },
  {
    id: 'c2',
    name: 'Safari Custom Land Rover',
    type: '4x4 Safari',
    transmission: 'Manual',
    capacity: 8,
    pricePerDay: 200,
    image: 'https://images.unsplash.com/photo-1533560271127-9fb61b4bc153?auto=format&fit=crop&q=80',
    country: Country.KENYA,
    district: 'Nairobi',
    features: ['Pop-up Roof', 'A/C', 'Radio', 'Winch']
  },
  {
    id: 'c3',
    name: 'Toyota RAV4',
    type: 'SUV',
    transmission: 'Automatic',
    capacity: 5,
    pricePerDay: 70,
    image: 'https://images.unsplash.com/photo-1568844293986-8d0400bd4745?auto=format&fit=crop&q=80',
    country: Country.UGANDA,
    district: 'Entebbe',
    features: ['A/C', 'Good on Fuel', 'Compact']
  },
  {
    id: 'c4',
    name: 'Mercedes-Benz Sprinter',
    type: 'Van',
    transmission: 'Automatic',
    capacity: 12,
    pricePerDay: 120,
    image: 'https://images.unsplash.com/photo-1554223040-593295feb8ee?auto=format&fit=crop&q=80',
    country: Country.TANZANIA,
    district: 'Dar es Salaam',
    features: ['Wi-Fi', 'Luxury Seats', 'A/C', 'TV']
  },
  {
    id: 'c5',
    name: 'Toyota Noah',
    type: 'Van',
    transmission: 'Automatic',
    capacity: 7,
    pricePerDay: 60,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80',
    country: Country.UGANDA,
    district: 'Jinja',
    features: ['A/C', 'Dual Sliders', 'Child Seats Available']
  },
  {
    id: 'c6',
    name: 'Toyota Corolla Cross',
    type: 'SUV',
    transmission: 'Automatic',
    capacity: 5,
    pricePerDay: 85,
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&q=80',
    country: Country.KENYA,
    district: 'Mombasa',
    features: ['Hybrid', 'A/C', 'Apple CarPlay']
  },
  {
    id: 'c7',
    name: 'Nissan X-Trail',
    type: 'SUV',
    transmission: 'Automatic',
    capacity: 5,
    pricePerDay: 90,
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80',
    country: Country.TANZANIA,
    district: 'Arusha',
    features: ['Panoramic Roof', '4WD', 'A/C']
  },
  {
    id: 'c8',
    name: 'Toyota Hiace',
    type: 'Van',
    transmission: 'Manual',
    capacity: 14,
    pricePerDay: 100,
    image: 'https://images.unsplash.com/photo-1600100397561-45607b3b4202?auto=format&fit=crop&q=80',
    country: Country.KENYA,
    district: 'Nairobi',
    features: ['Group Travel', 'Robust', 'Spacious']
  }
];

export const DISTRICTS: Record<Country, string[]> = {
  [Country.UGANDA]: ['Jinja', 'Kampala', 'Kabale', 'Entebbe'],
  [Country.KENYA]: ['Nairobi', 'Maasai Mara', 'Mombasa', 'Nakuru'],
  [Country.TANZANIA]: ['Dar es Salaam', 'Arusha', 'Zanzibar', 'Serengeti']
};

export const TOUR_ACTIVITIES: TourActivity[] = [
  // --- UGANDA (4) ---
  {
    id: 'ta1',
    name: 'Gorilla Trekking',
    description: 'An unforgettable encounter with the mountain gorillas in their natural habitat.',
    country: Country.UGANDA,
    location: 'Bwindi Impenetrable Forest',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80',
    price: 700,
    rating: 5.0,
    duration: 'Full Day',
    category: 'Trekking'
  },
  {
    id: 'ta2',
    name: 'White Water Rafting',
    description: 'Conquer the Grade 5 rapids of the mighty River Nile in Jinja.',
    country: Country.UGANDA,
    location: 'Jinja',
    image: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80',
    price: 140,
    rating: 4.9,
    duration: '6 Hours',
    category: 'Rafting'
  },
  {
    id: 'ta3',
    name: 'Chimpanzee Habituation',
    description: 'Spend a full day with chimpanzees and learn about their daily lives.',
    country: Country.UGANDA,
    location: 'Kibale National Park',
    image: 'https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?auto=format&fit=crop&q=80',
    price: 250,
    rating: 4.8,
    duration: 'Full Day',
    category: 'Wildlife'
  },
  {
    id: 'ta4',
    name: 'Murchison Falls Boat Cruise',
    description: 'A scenic boat trip to the base of the world\'s most powerful waterfall.',
    country: Country.UGANDA,
    location: 'Murchison Falls',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&q=80',
    price: 30,
    rating: 4.7,
    duration: '3 Hours',
    category: 'Photography'
  },
  // --- KENYA (4) ---
  {
    id: 'ta5',
    name: 'Maasai Mara Safari',
    description: 'Witness the Great Migration and the Big Five in Kenya\'s premier reserve.',
    country: Country.KENYA,
    location: 'Maasai Mara',
    image: 'https://images.unsplash.com/photo-1493246507139-91e8bef99c02?auto=format&fit=crop&q=80',
    price: 150,
    rating: 4.9,
    duration: 'Full Day',
    category: 'Wildlife'
  },
  {
    id: 'ta6',
    name: 'Hot Air Balloon Safari',
    description: 'Float over the Savannah at sunrise for a bird\'s eye view of the wildlife.',
    country: Country.KENYA,
    location: 'Maasai Mara',
    image: 'https://images.unsplash.com/photo-1516496636080-14fb876e029d?auto=format&fit=crop&q=80',
    price: 450,
    rating: 5.0,
    duration: '4 Hours',
    category: 'Photography'
  },
  {
    id: 'ta7',
    name: 'Diani Beach Camel Ride',
    description: 'Enjoy a peaceful ride along the white sands of Diani Beach.',
    country: Country.KENYA,
    location: 'Mombasa',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80',
    price: 25,
    rating: 4.6,
    duration: '1 Hour',
    category: 'Beach'
  },
  {
    id: 'ta8',
    name: 'Hell\'s Gate Cycling',
    description: 'Cycle among giraffes and zebras in this unique national park.',
    country: Country.KENYA,
    location: 'Naivasha',
    image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&q=80',
    price: 40,
    rating: 4.8,
    duration: '4 Hours',
    category: 'Hiking'
  },
  // --- TANZANIA (4) ---
  {
    id: 'ta9',
    name: 'Mount Kilimanjaro Hike',
    description: 'A challenging trek to the "Roof of Africa", the highest peak in the continent.',
    country: Country.TANZANIA,
    location: 'Kilimanjaro',
    image: 'https://images.unsplash.com/photo-1589553416260-178fa415973b?auto=format&fit=crop&q=80',
    price: 2500,
    rating: 5.0,
    duration: '7 Days',
    category: 'Trekking'
  },
  {
    id: 'ta10',
    name: 'Zanzibar Spice Tour',
    description: 'Discover the scents and flavors of the "Spice Island" on a guided farm tour.',
    country: Country.TANZANIA,
    location: 'Zanzibar',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80',
    price: 35,
    rating: 4.7,
    duration: '4 Hours',
    category: 'Relaxation'
  },
  {
    id: 'ta11',
    name: 'Ngorongoro Crater Drive',
    description: 'Explore the world\'s largest inactive volcanic caldera teeming with wildlife.',
    country: Country.TANZANIA,
    location: 'Ngorongoro',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&q=80',
    price: 200,
    rating: 4.9,
    duration: 'Full Day',
    category: 'Wildlife'
  },
  {
    id: 'ta12',
    name: 'Stone Town Walking Tour',
    description: 'Immerse yourself in the history and culture of Zanzibar\'s ancient city.',
    country: Country.TANZANIA,
    location: 'Zanzibar',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80',
    price: 20,
    rating: 4.8,
    duration: '3 Hours',
    category: 'Photography'
  }
];
